### ISSUE TITLE
How do i configure and run this code on my laptop 

### ISSUE THREAD

**Issue by KwesiGray** [Aaron-Ontoyin/Match-Fixtures#1]
How Do I configure and run this code on my laptop?

**Comment by Aaron-Ontoyin** [comment]
Take a look at the [readme](https://github.com/Aaron-Ontoyin/Match-Fixtures/blob/main/README.md).
You could also visit [here](https://match-fixtures.streamlit.app/)

**Comment by KwesiGray** [comment]
Okay Vibe
